version: '3.8'

services:
  krstenica-db:
    image: postgres:latest
    container_name: krstenica-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bokana
    volumes:
      - ./init-hram-db.sql:/docker-entrypoint-initdb.d/init.sql
      - krstenica_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  krstenica_data: